version: 2
project_name: interchange

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w
         -X main.Version=interchange/{{.Version}}
         -X templates.ServerVersionString=interchange/{{.Version}}"

archives:
  - formats: ['tar.gz']
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: grqphical
    name: interchange